version: '3'
services:
  gnpsfbmnclustergram-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnpsfbmngroupsselector-dash
    volumes:
      - ./logs:/app/logs:rw
    ports:
    - "5855:5000"
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh


networks:
  nginx-net:
    external:
      name: nginx-net